- name: enable EPEL repos
  yum: name=epel-release

- name: install python pip
  yum: name=python-pip

- name: install influxdb python library
  pip: name=influxdb

- name: wait for influxdb to be started
  wait_for: host={{ private_ip }} port=8086 timeout=60

- name: create influxdb admin user
  influxdb_user:
    login_host: "{{ influxdb_api_host }}"
    login_user: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    user: "{{ influxdb_admin_user }}"
    password: "{{ influxdb_admin_password }}"
    privilege: ALL

- name: create influxdb telegraf user
  influxdb_user:
    login_host: "{{ influxdb_api_host }}"
    login_user: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    user: "{{ influxdb_metrics_db_user }}"
    password: "{{ influxdb_metrics_db_password }}"
    database: telegraf
    privilege: ALL

- name: create retention policies
  influxdb_retention_policy:
    hostname: "{{ influxdb_api_host }}"
    username: "{{ influxdb_admin_user }}"
    password: "{{ influxdb_admin_password }}"
    database_name: telegraf
    policy_name: "{{ item.name }}"
    duration: "{{ item.duration }}"
    replication: "{{ item.replication }}"
    default: "{{ item.default | default(false) }}"
  with_items: "{{ influxdb_retention_policies }}"

- name: create downsamplings for influxdb measurements
  influxdb_downsample:
    login_host: "{{ influxdb_api_host }}"
    login_user: "{{ influxdb_admin_user }}"
    login_password: "{{ influxdb_admin_password }}"
    database: telegraf
    retentions: "{{ influxdb_retentions }}"
    measurements: "{{ influxdb_measurement_fields_to_downsample_on_mean }}"
    prune: true
