influxdb_api_host: "{{ hostvars[groups['influxdb'][0]]['private_ip'] }}"
influxdb_api_url: http://{{ influxdb_api_host }}:8086

influxdb_admin_user: admin
influxdb_admin_password: admin

influxdb_metrics_db: metrics
influxdb_metrics_db_user: metrics
influxdb_metrics_db_password: metrics
